name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Get latest code
        uses: actions/checkout@v4

      - name: 2. Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: 3. Install Dependencies
        run: npm install

      - name: 4. Build Project
        run: npm run build
        env:
           CI: false

      - name: 5. Upload to Hostinger
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          # IMPORTANT: If you use Vite, change ./build/ to ./dist/ below
          local-dir: ./build/
          server-dir: ./public_html/
          # SAFETY LOCK: This ensures your blogs folder is NEVER deleted
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            blogs/**
            blogs/**/*
            Blogs/**
            Blogs/**/*